# Site
repository: luiscruzr8/luiscruzr8.github.io
favicon: images/favicon.ico

# Personal info
name: Luis Cruz
title: Software Engineer
email: luisfernandocruzramos@gmail.com
website: luiscruzr8.github.io

# Dark Mode
darkmode: true

# Social links
# twitter_username: facespics
github_username:  luiscruzr8
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: luisfcr8
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
#about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, my name's Luis and I'm a Software Engineer. My main work experience is making software and web apps, but I'm eager to work in any kind of project. 
  I have worked at a couple of companies gaining teamwork and leadership skills. Still I keep learning everyday.

  I am most skilled in: <mark>Java</mark> , <mark>.Net</mark> and <mark>listening to music</mark>

# Projects Section
#projects_title: Projects

# Experience Section
#experience_title: Experience

# Education Section
#educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in software engineering some of my other interests and hobbies are:
   - Hanging out with friends
   - Movies and TV series
   - Gaming
   - Playing drums

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
